// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: media.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MediasService_GetProfilesMedias_FullMethodName = "/microblog.rpc.v1.MediasService/GetProfilesMedias"
)

// MediasServiceClient is the client API for MediasService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MediasServiceClient interface {
	GetProfilesMedias(ctx context.Context, in *GetProfilesMediasRequest, opts ...grpc.CallOption) (*GetProfilesMediasResponse, error)
}

type mediasServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMediasServiceClient(cc grpc.ClientConnInterface) MediasServiceClient {
	return &mediasServiceClient{cc}
}

func (c *mediasServiceClient) GetProfilesMedias(ctx context.Context, in *GetProfilesMediasRequest, opts ...grpc.CallOption) (*GetProfilesMediasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProfilesMediasResponse)
	err := c.cc.Invoke(ctx, MediasService_GetProfilesMedias_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MediasServiceServer is the server API for MediasService service.
// All implementations must embed UnimplementedMediasServiceServer
// for forward compatibility.
type MediasServiceServer interface {
	GetProfilesMedias(context.Context, *GetProfilesMediasRequest) (*GetProfilesMediasResponse, error)
	mustEmbedUnimplementedMediasServiceServer()
}

// UnimplementedMediasServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMediasServiceServer struct{}

func (UnimplementedMediasServiceServer) GetProfilesMedias(context.Context, *GetProfilesMediasRequest) (*GetProfilesMediasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfilesMedias not implemented")
}
func (UnimplementedMediasServiceServer) mustEmbedUnimplementedMediasServiceServer() {}
func (UnimplementedMediasServiceServer) testEmbeddedByValue()                       {}

// UnsafeMediasServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MediasServiceServer will
// result in compilation errors.
type UnsafeMediasServiceServer interface {
	mustEmbedUnimplementedMediasServiceServer()
}

func RegisterMediasServiceServer(s grpc.ServiceRegistrar, srv MediasServiceServer) {
	// If the following call pancis, it indicates UnimplementedMediasServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MediasService_ServiceDesc, srv)
}

func _MediasService_GetProfilesMedias_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfilesMediasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediasServiceServer).GetProfilesMedias(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediasService_GetProfilesMedias_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediasServiceServer).GetProfilesMedias(ctx, req.(*GetProfilesMediasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MediasService_ServiceDesc is the grpc.ServiceDesc for MediasService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MediasService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "microblog.rpc.v1.MediasService",
	HandlerType: (*MediasServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProfilesMedias",
			Handler:    _MediasService_GetProfilesMedias_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "media.proto",
}
